crm/urls.py
from django.conf.urls import url

from crm import views
app_name = 'crm'

urlpatterns = [
    url(r'^$', views.ContractListView.as_view(), name="contracts_list"),

    url(r'^contract_add/$', views.ContractCreateView.as_view(), name='contract_add'),
    url(r'^contract/(?P<contract_id>\w+)/$', views.contract_view, name='contract_view'),
    url(r'^contract/(?P<contract_id>\w+)/contract_edit/$', views.contract_edit, name='contract_edit'),
    url(r'^contract/(?P<contract_id>\w+)/history/$', views.contract_history, name='contract_history'),
    ]

ich_bau/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from django.contrib import admin

from .views import get_homepage

from .profiles.views import ProfileCreateView, ProfileCreateSubView, ProfileDetailView, ProfileUpdateView, my_profile_view, ProfileEditView, ProfileListView, notifications_view_unread, notifications_view_unread_by_type, notifications_view_read, notification_read

urlpatterns = [
    url(r"^$", get_homepage, name="home"),
    url(r"^admin/", admin.site.urls),
    url(r"^account/", include("account.urls")),
    url(r'^summernote/', include('django_summernote.urls')),

    url(r"^profile/view/", my_profile_view, name="my_profile_view"),
    url(r"^profile/edit/", ProfileEditView.as_view(), name="profiles_edit"),
    url(r"^p/$", ProfileListView.as_view(), name="profiles_list"),
    url(r"^p/(?P<pk>\w+)/$", ProfileDetailView.as_view(), name="profiles_detail"),
    url(r"^p/(?P<pk>\w+)/edit/$", ProfileUpdateView.as_view(), name="profile_update"),
    url(r"^p/create$", ProfileCreateView.as_view(), name="profile_create"),
    url(r"^p/(?P<pk>\w+)/add_sub/$", ProfileCreateSubView.as_view(), name="profile_add_sub"),
    url(r"^p/(?P<pk>\w+)/level/(?P<level_pk>\w+)/add_sub/$", ProfileCreateSubView.as_view(), name="profile_add_sub_tree_view"),

    url(r"^notifications/$", notifications_view_unread, name="unread_notifications_view"),
    url(r"^notifications_by_type/$", notifications_view_unread_by_type, name="unread_notifications_view_by_type"),
    url(r"^notifications/read/$", notifications_view_read, name="read_notifications_view"),
    url(r"^notification/(?P<notification_id>\w+)/$", notification_read, name="notification_read"),

    url(r"^support/", include('support.urls', namespace="support") ),
    url(r"^project/", include('project.urls', namespace="project") ),
    url(r"^crm/", include('crm.urls', namespace="crm") ),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/urls.py
from django.conf.urls import url
from django.urls import path

from project import views

app_name = 'project'

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^all_available/$', views.index_available, name='all_available'),
    url(r'^all_public/$', views.index_public, name='all_public'),
    url(r'^search_public/$', views.index_search_public, name='search_public'),
    url(r'^task_search/$', views.index_task_search, name='task_search'),
    url(r'^task_search_by_domain/$', views.index_task_search_by_domain, name='task_search_by_domain'),
    url(r'^task_search_by_domain/selected/(?P<domain_id>\w+)/$', views.index_task_search_by_domain, name='task_search_by_domain_selected'),

    url(r'^project_add/$', views.ProjectCreateView.as_view(), name='project_add'),
    url(r'^project/(?P<project_id>\w+)/project_edit/$', views.project_edit, name='project_edit'),

    url(r'^project/(?P<project_id>\w+)/$', views.project_view, name='project_view'),
    url(r'^project/(?P<project_id>\w+)/history/$', views.project_history, name='project_history'),
    url(r'^project/(?P<project_id>\w+)/closed_task/$', views.project_view_closed_tasks, name='project_view_closed_tasks'),
    url(r'^project/(?P<project_id>\w+)/assigned_task/$', views.project_view_assigned_tasks, name='project_view_assigned_tasks'),
    url(r'^project/(?P<project_id>\w+)/unassigned_task/$', views.project_view_unassigned_tasks, name='project_view_unassigned_tasks'),

    # django v.2 path
    path( 'project/<project_id>/task_by_domain/', views.project_view_task_by_domain, name='project_view_task_by_domain'),
    path( 'project/<project_id>/task_by_domain/<domain_id>/', views.project_view_task_by_domain, name='project_view_task_for_domain'),

    url(r'^project/(?P<project_id>\w+)/search_task/$', views.project_view_search_tasks, name='project_view_search_tasks'),

    url(r'^project/(?P<project_id>\w+)/last_actions/$', views.project_view_last_actions, name='project_view_last_actions'),
    url(r'^project/(?P<project_id>\w+)/sub_projects/$', views.project_view_sub_projects, name='project_view_sub_projects'),
    url(r'^project/(?P<project_id>\w+)/members/$', views.project_view_members, name='project_view_members'),
    url(r'^project/(?P<project_id>\w+)/milestones/$', views.project_view_milestones, name='project_view_milestones'),
    url(r'^project/(?P<project_id>\w+)/reports/$', views.project_view_reports, name='project_view_reports'),

    url(r'^project/(?P<project_id>\w+)/report_all_tasks/$', views.project_view_report_all_tasks, name='project_view_report_all_tasks'),
    url(r'^project/(?P<project_id>\w+)/report_all_tasks_xls/$', views.project_view_report_all_tasks_xls.as_view(), name='project_view_report_all_tasks_xls'),
    # repo urls
    url(r'^project/(?P<project_id>\w+)/files/$', views.project_view_files, name='project_view_files'),
    url(r'^project/(?P<project_id>\w+)/files/commit/(?P<rev_id>\w+)/$', views.project_view_file_commit_view, name='project_view_file_commit_view'),
    url(r'^project/(?P<project_id>\w+)/create_repo/$', views.project_create_repo, name='project_create_repo'),

    url(r'^member_add/(?P<project_id>\w+)/$', views.AddMemberCreateView.as_view(), name='member_add'),
    url(r'^member_want_join/(?P<project_id>\w+)/$', views.member_want_join, name='member_want_join'),
    url(r'^member/(?P<member_id>\w+)/member_accept/$', views.member_accept, name='member_accept'),
    url(r'^member/(?P<member_id>\w+)/team_accept/$', views.team_accept, name='team_accept'),
    url(r'^member/(?P<member_id>\w+)/remove_check/$', views.member_remove_check, name='member_remove_check'),
    url(r'^member/(?P<member_id>\w+)/remove_confirm/$', views.member_remove_confirm, name='member_remove_confirm'),

    url(r'^task_add/(?P<project_id>\w+)/$', views.TaskCreateView.as_view(), name='task_add'),
    url(r'^task_add_to_milestone/(?P<milestone_id>\w+)/$', views.TaskCreateView.as_view(), name='task_add_to_milestone'),
    url(r'^task/(?P<pk>\w+)/edit/$', views.TaskUpdateView.as_view(), name='task_edit'),
    url(r'^task/(?P<task_id>\w+)/checklist/$', views.task_checklist, name='task_checklist'),
    url(r'^task/(?P<task_id>\w+)/$', views.task_view, name='task_view'),
    url(r'^task/(?P<task_id>\w+)/history/$', views.task_history, name='task_history'),
    url(r'^add_linked/(?P<task_id>\w+)/$', views.add_linked, name='add_linked'),

    url(r'^task/(?P<task_id>\w+)/add_property/$', views.task_add_property, name='task_add_property'),
    url(r'^task/(?P<task_property_id>\w+)/edit_property/$', views.task_edit_property, name='task_edit_property'),

    url(r'^sub_project_add/(?P<project_id>\w+)/$', views.Sub_ProjectCreateView.as_view(), name='sub_project_add'),
    url(r'^sub_project/(?P<sub_project_id>\w+)/$', views.sub_project_view, name='sub_project_view'),
    url(r'^sub_project/(?P<pk>\w+)/edit/$', views.Sub_ProjectUpdateView.as_view(), name='sub_project_edit'),
    url(r'^sub_project/(?P<sub_project_id>\w+)/history/$', views.sub_project_history, name='sub_project_history'),

    url(r'^task_move2project_dialog/(?P<task_id>\w+)/$', views.task_move2project, name='task_move2project_dialog'),
    url(r'^task_move2project_check/(?P<task_id>\w+)/target_project/(?P<project_id>\w+)/$', views.task_move2project, name='task_move2project_check'),

    url(r'^add_profile/(?P<task_id>\w+)/$', views.add_profile, name='add_profile'),
    url(r'^add_profile/(?P<task_id>\w+)/level/(?P<level_pk>\w+)/$', views.add_profile, name='add_profile_sub_tree_view'),
    url(r'^add_user/(?P<task_id>\w+)/$', views.add_user, name='add_user'),
    url(r'^switch_assign_responsibillty/(?P<taskprofile_id>\w+)/priority/(?P<priority_int>\w+)/$', views.switch_assign_responsibillty, name='switch_assign_responsibillty'),
    url(r'^remove_assign_responsibillty/(?P<taskprofile_id>\w+)/$', views.remove_assign_responsibillty, name='remove_assign_responsibillty'),

    url(r'^add_domain/(?P<task_id>\w+)/$', views.add_domain, name='add_domain'),

    url(r'^task_link/(?P<tasklink_id>\w+)/unlink/$', views.task_unlink, name='task_unlink'),

    path( 'task_domain/<taskdomain_id>/unlink', views.project_task_domain_unlink, name='project_task_domain_unlink'),

    url(r'^task_comment/(?P<task_comment_id>\w+)/edit/$', views.edit_task_comment, name='edit_task_comment'),
    url(r'^task_comment/(?P<task_comment_id>\w+)/history/$', views.task_comment_history, name='task_comment_history'),

    url(r'^task_check/(?P<task_check_id>\w+)/switch/$', views.task_check_switch, name='task_check_switch'),

    url(r'^milestone_add/(?P<project_id>\w+)/$', views.MilestoneCreateView.as_view(), name='milestone_add'),
    url(r'^milestone/(?P<pk>\w+)/edit/$', views.MilestoneUpdateView.as_view(), name='milestone_edit'),
    url(r'^milestone/(?P<milestone_id>\w+)/$', views.milestone_view, name='milestone_view'),
    url(r'^milestone/(?P<milestone_id>\w+)/history/$', views.milestone_history, name='milestone_history'),

    url(r'^schedule/view_my_index/$', views.view_my_schedule, name='view_my_index_schedule'),
    url(r'^schedule/view_profile_index/(?P<profile_id>\w+)/$', views.view_profile_schedule, name='view_profile_schedule'),
    url(r'^schedule_add_current/$', views.create_schedule_current, name='create_schedule_current'),
    url(r'^schedule_add_current/(?P<profile_id>\w+)/$', views.create_schedule_current, name='create_schedule_current'),
    url(r'^schedule_add_next/$', views.create_schedule_next, name='create_schedule_next'),
    url(r'^schedule_add_next/(?P<profile_id>\w+)/$', views.create_schedule_next, name='create_schedule_next'),
    url(r'^schedule/(?P<schedule_item_id>\w+)/$', views.schedule_item_view, name='schedule_item_view'),

    url(r'^schedule/(?P<schedule_item_id>\w+)/schedule_one_task/(?P<task_id>\w+)$', views.schedule_one_task, name='schedule_one_task'),
    url(r'^schedule/(?P<schedule_item_id>\w+)/unschedule_one_task/(?P<task_id>\w+)$', views.unschedule_one_task, name='unschedule_one_task'),

    ]

property/models.py
from django.db import models

#from ybase.avatars import enumerable_variant_upload
enumerable_variant_upload = ''

# Create your models here.

# Enumerable

class EnumerableProperty(models.Model):
    fullname = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['fullname']

    def __str__(self):
        return self.fullname

    # def get_absolute_url(self):
        # return "/property/enum/%i/" % self.id

#Простой вызов `from product.models import Product` выдает ошибку, вилимо получается циклическая связь. Поэтому - трюк ForeignKey( 'product.Product' )

class EnumerableVariants(models.Model):
    enumerable_property = models.ForeignKey(EnumerableProperty, on_delete=models.PROTECT, blank=False, null=False )
    fullname = models.CharField(max_length=255)
    #clarifying_product=models.ForeignKey( 'product.Product', on_delete=models.PROTECT, blank=True, null=True )
    avatar = models.ImageField(upload_to=enumerable_variant_upload, blank=True, null=True )

    class Meta:
        ordering = ['fullname']

    def __str__(self):
        return self.fullname

    # def get_absolute_url(self):
        # return "/property/enum/var/%i/" % self.id

# Physical

class Quantity(models.Model):
    fullname = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['fullname']

    def __str__(self):
        return self.fullname
    # def get_absolute_url(self):
        # return "/property/quantity/%i/" % self.id

class MeasurementUnits(models.Model):
    quantity = models.ForeignKey(Quantity, on_delete=models.PROTECT)
    shortname = models.CharField(max_length=25)
    fullname = models.CharField(max_length=255)
    # kilogram to gram
    factor = models.FloatField()
    # Fahrenheit to Celsius scale
    shift_scale = models.FloatField(blank=True, null=True)
    # for sample
    # Kilogram to gram : factor = 1000
    # Fahrenheit to Celsius scale : faltor = 5/9, shift_scale = -32

    def __str__(self):
        return self.fullname

    # def get_absolute_url(self):
        # return "/property/quantity/unit/%i/" % self.id

    # пересчитывает в базовые, с учетом factor и shift_scale
    def calc_factored( self, a_amount ):
        if ( a_amount is None ):
            return None
        else:
            r = a_amount
            if not( self.shift_scale is None ):
                r = r + self.shift_scale
            if self.factor != 0:
                r = r * self.factor
            return r

class PhysicalProperty(models.Model):
    quantity = models.ForeignKey(Quantity, on_delete=models.PROTECT)
    fullname = models.CharField(max_length=255)
    default_unit = models.ForeignKey(MeasurementUnits, on_delete=models.PROTECT)

    class Meta:
        ordering = ['fullname']

    def __str__(self):
        return self.fullname

    # def get_absolute_url(self):
        # return "/property/quantity/pp/%i/" % self.id

    # получить список допустимых единиц
    def linked_mu(self):
        return MeasurementUnits.objects.filter( quantity = self.quantity )

    # проверки перед сохранением
    def save(self, *args, **kwargs):
        # проверить - есть ли данная величина у указанной единицы?
        if self.default_unit.quantity == self.quantity:
            super(PhysicalProperty, self).save(*args, **kwargs) # Call the "real" save() method.
        else:
            raise Exception("Wrong measure unit!")

# условия измерения
class PPMeasurementCondition(models.Model):
    measured_pp = models.ForeignKey(PhysicalProperty, on_delete=models.PROTECT, related_name = 'measured_pp' )
    # для измерения measured_pp нужно зафиксировать значение fixed_pp.
    fixed_pp = models.ForeignKey(PhysicalProperty, on_delete=models.PROTECT, related_name = 'fixed_pp' )
    amount=models.FloatField()
    amount_based=models.FloatField() # значение пересчитанное в базовые единицы
    amount_unit=models.ForeignKey(MeasurementUnits, on_delete=models.PROTECT)

    class Meta:
        ordering = ['measured_pp', 'amount_based']

    # def get_absolute_url(self):
        # return "/property/quantity/pp/mc/%i/" % self.id

    def __str__(self):
        return str( self.fixed_pp ) + " " + str( self.amount ) + " " + str( self.amount_unit )

    def save(self, *args, **kwargs):
        # проверки
        if self.measured_pp == self.fixed_pp:
            # нельзя связывать сам с собой
            raise Exception( "Can't set measurement condition to itself!" )
        if self.amount_unit.quantity != self.fixed_pp.quantity:
            raise Exception( "Wrong unit!" )

        self.amount_based = self.amount_unit.calc_factored( self.amount )
        super(PPMeasurementCondition, self).save(*args, **kwargs) # Call the "real" save() method.

ich_bau/templates/profiles/notifications.html
{% extends "site_base.html" %}

{% block head_title %}Notifications{% endblock %}

{% load thumbnail %}

{% block body %}
    <div class="row">
<div class="col-md-12">

<h1>Notifications</h1>

<ul class="nav nav-tabs">
  <li role="presentation" {% if filter_name == 'new_by_user' %} class="active" {% endif %}><a href="{% url 'unread_notifications_view' %}">New</a></li>
  <li role="presentation" {% if filter_name == 'new_by_type' %} class="active" {% endif %}><a href="{% url 'unread_notifications_view_by_type' %}">New by type</a></li>
  <li role="presentation" {% if filter_name == 'old' %} class="active" {% endif %}><a href="{% url 'read_notifications_view' %}">Old</a></li>
</ul>

<p></p>

{% if filter_name == 'new_by_user' %}

{% regroup notifications by sender_user as nlist %}

<ul>
{% for nsender_user in nlist %}
    <li>{{ nsender_user.grouper }}
    <ol>
        {% for n in nsender_user.list %}
         <li><a href="{{n.get_absolute_url}}">{{n.decode_msg}}</a> {{n.created_at}} by {{n.sender_user}}</li>
        {% endfor %}
    </ol>
    </li>
{% endfor %}
</ul>

{% else %}

{% if filter_name == 'new_by_type' %}

{% regroup notifications by content_type as nlist %}

<ul>
{% for ncontent_type in nlist %}
    <li><strong>{{ ncontent_type.grouper }}</strong>
    <ul>
        {% regroup ncontent_type.list by object_id as n_object_list %}
        {% for n_object in n_object_list %}
            <li><strong>{{n_object.list.0.get_title}}</strong>
            <ol>
            {% for n in n_object.list %}
             <li>
             <a href="{{n.get_absolute_url}}">{{n.decode_msg}}</a> {{n.created_at}} by {{n.sender_user}}</li>
            {% endfor %}
            </ol>
            </li>
        {% endfor %}

    </ul>
    </li>
{% endfor %}
</ul>




{% else %}
<ol>
{% for n in notifications %}
  <li><a href="{{n.get_absolute_url}}">{{n.decode_msg}}</a> {{n.created_at}} by {{n.sender_user}}</li>
{% endfor %}
</ol>

<p>Last {{OLD_NOTIFICATIONS_VIEW_LIMIT}} notifications shown.</p>

{% endif %}
{% endif %}


    </div>
    </div>

{% endblock %}

ich_bau/templates/profiles/profile_detail.html
{% extends "site_base.html" %}

{% load profile_tag %}

{% block head_title %}{{ profile.display_name }}{% endblock %}

{% load thumbnail %}

{% block body %}
    <div class="row">
        <div class="col-md-4">
            <div class="profile-widget">
                {% if profile.avatar %}
                    <img class="img-polaroid avatar hidden-phone" src="{% thumbnail profile.avatar 160x160 crop %}" alt="{{ profile.name }}">
                {% else %}
                    {% fa_profile_icon profile.profile_type %}
                {% endif %}

                <h2>{{ profile.display_name }}</h2>

                <div class="profile">
                    {% if profile.description %}
                        <div class="bio">
                            {{ profile.description_html|safe}}
                        </div>
                    {% endif %}
                    {% if profile.location %}
                        <div class="item">
                            <span class="dim">
                                <i class="fa fa-map-marker"></i>
                            </span>
                            {{ profile.location }}
                        </div>
                    {% endif %}
                    {% if profile.website %}
                        <div class="item">
                            <span class="dim">
                                <i class="fa fa-external-link"></i>
                            </span>
                            <a href="{{ profile.website }}">{{ profile.website }}</a>
                        </div>
                    {% endif %}
                    {%if profile.user%}
                        <div class="item">
                            <span class="dim">
                                <i class="fa fa-clock-o"></i>
                                Joined on
                            </span>
                            {{ profile.user.date_joined }}
                        </div>
                        {% if not profile.user.is_active %}
                            <div class="item">
                                <strong>User is NOT active</strong>
                            </div>
                        {%endif%}
                    {%endif%}
                    {% if request.user == profile.user %}
                        {% if user_repo_pw %}
                        <div class="item">
                            <span class="dim">
                                <i class="fa fa-key"></i>
                                Your repo password:
                            </span>
                            {{ user_repo_pw }}
                        </div>
                        {% endif %}
                        <a href="{% url 'profiles_edit' %}" class="btn btn-default btn-xs"><i class="fa fa-pencil"></i> Edit My Profile</a>
                    {% else %}
                        {% if not profile.has_account %}
                            <a href="{% url 'profile_update' pk=profile.pk %}" class="btn btn-default btn-xs"><i class="fa fa-pencil"></i> Edit Profile</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-4">
        <h2>Main profiles</h2>
        {% if main_profiles %}
        <ul>
        {% for mp in main_profiles %}
        <li><a href="{% url 'profiles_detail' pk=mp.main_profile.id %}">

            {% if mp.main_profile.avatar %}
                <img width="72" height="72" class="media-object pull-left" src="{% thumbnail mp.main_profile.avatar 72x72 crop %}">
            {% else %}
                {% fa_profile_icon mp.main_profile.profile_type %}
            {% endif %}

        {{ mp.main_profile.display_name }}</a></li>
        {% endfor %}
        </ul>
        {% endif %}
        <h2>Sub profiles</h2>
        {% if sub_profiles %}
        <ul>
        {% for sp in sub_profiles %}
        <li><a href="{% url 'profiles_detail' pk=sp.sub_profile.id %}">
            {% if sp.sub_profile.avatar %}
                <img width="72" height="72" class="media-object pull-left" src="{% thumbnail sp.sub_profile.avatar 72x72 crop %}">
            {% else %}
                {% fa_profile_icon sp.sub_profile.profile_type %}
            {% endif %}

        {{ sp.sub_profile.display_name }}</a></li>
        {% endfor %}
        </ul>
        {% endif %}
        <a href="{% url 'profile_add_sub' pk=profile.id %}" class="btn btn-default btn-xs"><i class="fa fa-pencil"></i> Add sub</a>
        </div>
        <h2>Mannaging profiles</h2>
        {% if managed_profiles %}
        {% for cp in managed_profiles %}
        <li><a href="{% url 'profiles_detail' pk=cp.managed_profile.id %}">{{ cp.managed_profile.display_name }}</a>
            {% if request.user == profile.user %}
               - <a href="{% url 'project:view_profile_schedule' profile_id=cp.managed_profile.id %}" class="btn btn-default" role="button">view {{cp.managed_profile}} schedule</a>
            {% endif %}
        </li>
        {% endfor %}
        {% endif %}
        <h2>Managed by users</h2>
        {% if managed_by_user %}
        {% for cu in managed_by_user %}
        <li><a href="{% url 'profiles_detail' pk=cu.manager_user.profile.id %}">{{ cu.manager_user.profile.display_name }}</a></li>
        {% endfor %}
        {% endif %}
    </div>

    {% if profile.could_has_task %}
        <div class="row">
            <div class="col-md-12">
                <h3>
                {% if view_projects_and_tasks_header == 'to_you' %}
                    Projects and tasks assigned to you
                {% else %}
                    {% if view_projects_and_tasks_header == 'to_managed' %}
                        Projects and tasks assigned to managed profiles
                    {% else %}
                        {% if view_projects_and_tasks_header == 'to_profile' %}
                            Projects and tasks assigned to profile (for projects available for you)
                        {% endif %}
                    {% endif %}
                {% endif %}
                </h3>

                   {% if view_projects_and_tasks_header == 'to_managed' %}
                       <p><a href="{% url 'project:view_profile_schedule' profile_id=profile.id %}" class="btn btn-default" role="button">View {{profile}} schedule</a></p>
                   {% endif %}

                    {% if profile_projects %}
                    <h4>Projects</h4>
                        <ul>
                        {% for pp in profile_projects %}
                            <li><a href="{% url 'project:project_view_members' pp.pk %}">{{pp}}</a></li>
                        {% endfor %}
                        </ul>
                    {% endif %}

                    {% if profile_tasks %}
                        <h4>Tasks</h4>
                        {% include "project/task_list.html" with table_mode='index' tasks=profile_tasks %}
                    {%  endif %}
            </div>
        </div >
    {% endif %}

{% endblock %}

ich_bau/templates/profiles/profile_form.html
{% extends "site_base.html" %}

{% load thumbnail %}
{% load bootstrap %}

{% block body_class %}{{ block.super }} profile{% endblock %}

{% block head_title %}Edit Profile{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-9">
            <form class="form profile-form" action="" method="POST" enctype="multipart/form-data">
                {% if profile %}
                <legend>Edit Profile</legend>
                {% else %}
                <legend>Create Profile</legend>
                {% endif %}
                {% csrf_token %}

                {% if profile.user == request.user %}
                {% else %}
                {{ form.profile_type|bootstrap }}
                {% endif %}

                {{ form.name|bootstrap }}
                <div id="div_id_avatar" class="control-group">
                    <label for="id_avatar" class="control-label">
                        Avatar
                    </label>
                    <div class="controls">
                        {% if profile.avatar %}
                            <img class="img-polaroid avatar hidden-phone" src="{% thumbnail profile.avatar 160x160 crop %}" alt="{{ profile.name }}" /><br />
                        {% endif %}
                        {% comment %}
                        <div class="preview-window" style="margin-top:20px;width:160px;height:160px;overflow:hidden;float:left;">
                            <img id="preview" style="max-width: none;" class="hide" src="" />
                        </div>
                        {% endcomment %}
                        {% comment %}
                        <div class="remove">
                            <label for="avatar-clear_id">Clear Avatar</label>
                            <input id="avatar-clear_id" name="avatar-clear" type="checkbox">
                        </div>
                        {% endcomment %}
                        <span class="btn btn-success btn-avatar btn-small">
                            <span>Select File</span>
                            <input id="id_avatar" name="avatar" type="file">
                        </span>
                        <span class="selected-filename"></span>
                    </div>
                </div>
                {{ form.description|bootstrap }}
                {{ form.location|bootstrap }}
                {{ form.website|bootstrap }}
                <button type="submit" class="btn btn-primary">Save</button>
                {% if profile %}
                    <a class="btn btn-default" href="{% url 'profiles_detail' pk=profile.id %}">Cancel</a>
                {% endif %}
            </form>
        </div>
    </div>
{% endblock %}