crm/urls.py
from django.conf.urls import url

from crm import views
app_name = 'crm'

urlpatterns = [
    url(r'^$', views.ContractListView.as_view(), name="contracts_list"),

    url(r'^contract_add/$', views.ContractCreateView.as_view(), name='contract_add'),
    url(r'^contract/(?P<contract_id>\w+)/$', views.contract_view, name='contract_view'),
    url(r'^contract/(?P<contract_id>\w+)/contract_edit/$', views.contract_edit, name='contract_edit'),
    url(r'^contract/(?P<contract_id>\w+)/history/$', views.contract_history, name='contract_history'),
    ]

ich_bau/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from django.contrib import admin

from .views import get_homepage

from .profiles.views import ProfileCreateView, ProfileCreateSubView, ProfileDetailView, ProfileUpdateView, my_profile_view, ProfileEditView, ProfileListView, notifications_view_unread, notifications_view_unread_by_type, notifications_view_read, notification_read

urlpatterns = [
    url(r"^$", get_homepage, name="home"),
    url(r"^admin/", admin.site.urls),
    url(r"^account/", include("account.urls")),
    url(r'^summernote/', include('django_summernote.urls')),

    url(r"^profile/view/", my_profile_view, name="my_profile_view"),
    url(r"^profile/edit/", ProfileEditView.as_view(), name="profiles_edit"),
    url(r"^p/$", ProfileListView.as_view(), name="profiles_list"),
    url(r"^p/(?P<pk>\w+)/$", ProfileDetailView.as_view(), name="profiles_detail"),
    url(r"^p/(?P<pk>\w+)/edit/$", ProfileUpdateView.as_view(), name="profile_update"),
    url(r"^p/create$", ProfileCreateView.as_view(), name="profile_create"),
    url(r"^p/(?P<pk>\w+)/add_sub/$", ProfileCreateSubView.as_view(), name="profile_add_sub"),
    url(r"^p/(?P<pk>\w+)/level/(?P<level_pk>\w+)/add_sub/$", ProfileCreateSubView.as_view(), name="profile_add_sub_tree_view"),

    url(r"^notifications/$", notifications_view_unread, name="unread_notifications_view"),
    url(r"^notifications_by_type/$", notifications_view_unread_by_type, name="unread_notifications_view_by_type"),
    url(r"^notifications/read/$", notifications_view_read, name="read_notifications_view"),
    url(r"^notification/(?P<notification_id>\w+)/$", notification_read, name="notification_read"),

    url(r"^support/", include('support.urls', namespace="support") ),
    url(r"^project/", include('project.urls', namespace="project") ),
    url(r"^crm/", include('crm.urls', namespace="crm") ),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/urls.py
from django.conf.urls import url
from django.urls import path

from project import views

app_name = 'project'

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^all_available/$', views.index_available, name='all_available'),
    url(r'^all_public/$', views.index_public, name='all_public'),
    url(r'^search_public/$', views.index_search_public, name='search_public'),
    url(r'^task_search/$', views.index_task_search, name='task_search'),
    url(r'^task_search_by_domain/$', views.index_task_search_by_domain, name='task_search_by_domain'),
    url(r'^task_search_by_domain/selected/(?P<domain_id>\w+)/$', views.index_task_search_by_domain, name='task_search_by_domain_selected'),

    url(r'^project_add/$', views.ProjectCreateView.as_view(), name='project_add'),
    url(r'^project/(?P<project_id>\w+)/project_edit/$', views.project_edit, name='project_edit'),

    url(r'^project/(?P<project_id>\w+)/$', views.project_view, name='project_view'),
    url(r'^project/(?P<project_id>\w+)/history/$', views.project_history, name='project_history'),
    url(r'^project/(?P<project_id>\w+)/closed_task/$', views.project_view_closed_tasks, name='project_view_closed_tasks'),
    url(r'^project/(?P<project_id>\w+)/assigned_task/$', views.project_view_assigned_tasks, name='project_view_assigned_tasks'),
    url(r'^project/(?P<project_id>\w+)/unassigned_task/$', views.project_view_unassigned_tasks, name='project_view_unassigned_tasks'),

    # django v.2 path
    path( 'project/<project_id>/task_by_domain/', views.project_view_task_by_domain, name='project_view_task_by_domain'),
    path( 'project/<project_id>/task_by_domain/<domain_id>/', views.project_view_task_by_domain, name='project_view_task_for_domain'),

    url(r'^project/(?P<project_id>\w+)/search_task/$', views.project_view_search_tasks, name='project_view_search_tasks'),

    url(r'^project/(?P<project_id>\w+)/last_actions/$', views.project_view_last_actions, name='project_view_last_actions'),
    url(r'^project/(?P<project_id>\w+)/sub_projects/$', views.project_view_sub_projects, name='project_view_sub_projects'),
    url(r'^project/(?P<project_id>\w+)/members/$', views.project_view_members, name='project_view_members'),
    url(r'^project/(?P<project_id>\w+)/milestones/$', views.project_view_milestones, name='project_view_milestones'),
    url(r'^project/(?P<project_id>\w+)/reports/$', views.project_view_reports, name='project_view_reports'),

    url(r'^project/(?P<project_id>\w+)/report_all_tasks/$', views.project_view_report_all_tasks, name='project_view_report_all_tasks'),
    url(r'^project/(?P<project_id>\w+)/report_all_tasks_xls/$', views.project_view_report_all_tasks_xls.as_view(), name='project_view_report_all_tasks_xls'),
    # repo urls
    url(r'^project/(?P<project_id>\w+)/files/$', views.project_view_files, name='project_view_files'),
    url(r'^project/(?P<project_id>\w+)/files/commit/(?P<rev_id>\w+)/$', views.project_view_file_commit_view, name='project_view_file_commit_view'),
    url(r'^project/(?P<project_id>\w+)/create_repo/$', views.project_create_repo, name='project_create_repo'),

    url(r'^member_add/(?P<project_id>\w+)/$', views.AddMemberCreateView.as_view(), name='member_add'),
    url(r'^member_want_join/(?P<project_id>\w+)/$', views.member_want_join, name='member_want_join'),
    url(r'^member/(?P<member_id>\w+)/member_accept/$', views.member_accept, name='member_accept'),
    url(r'^member/(?P<member_id>\w+)/team_accept/$', views.team_accept, name='team_accept'),
    url(r'^member/(?P<member_id>\w+)/remove_check/$', views.member_remove_check, name='member_remove_check'),
    url(r'^member/(?P<member_id>\w+)/remove_confirm/$', views.member_remove_confirm, name='member_remove_confirm'),

    url(r'^task_add/(?P<project_id>\w+)/$', views.TaskCreateView.as_view(), name='task_add'),
    url(r'^task_add_to_milestone/(?P<milestone_id>\w+)/$', views.TaskCreateView.as_view(), name='task_add_to_milestone'),
    url(r'^task/(?P<pk>\w+)/edit/$', views.TaskUpdateView.as_view(), name='task_edit'),
    url(r'^task/(?P<task_id>\w+)/checklist/$', views.task_checklist, name='task_checklist'),
    url(r'^task/(?P<task_id>\w+)/$', views.task_view, name='task_view'),
    url(r'^task/(?P<task_id>\w+)/history/$', views.task_history, name='task_history'),
    url(r'^add_linked/(?P<task_id>\w+)/$', views.add_linked, name='add_linked'),

    url(r'^task/(?P<task_id>\w+)/add_property/$', views.task_add_property, name='task_add_property'),
    url(r'^task/(?P<task_property_id>\w+)/edit_property/$', views.task_edit_property, name='task_edit_property'),

    url(r'^sub_project_add/(?P<project_id>\w+)/$', views.Sub_ProjectCreateView.as_view(), name='sub_project_add'),
    url(r'^sub_project/(?P<sub_project_id>\w+)/$', views.sub_project_view, name='sub_project_view'),
    url(r'^sub_project/(?P<pk>\w+)/edit/$', views.Sub_ProjectUpdateView.as_view(), name='sub_project_edit'),
    url(r'^sub_project/(?P<sub_project_id>\w+)/history/$', views.sub_project_history, name='sub_project_history'),

    url(r'^task_move2project_dialog/(?P<task_id>\w+)/$', views.task_move2project, name='task_move2project_dialog'),
    url(r'^task_move2project_check/(?P<task_id>\w+)/target_project/(?P<project_id>\w+)/$', views.task_move2project, name='task_move2project_check'),

    url(r'^add_profile/(?P<task_id>\w+)/$', views.add_profile, name='add_profile'),
    url(r'^add_profile/(?P<task_id>\w+)/level/(?P<level_pk>\w+)/$', views.add_profile, name='add_profile_sub_tree_view'),
    url(r'^add_user/(?P<task_id>\w+)/$', views.add_user, name='add_user'),
    url(r'^switch_assign_responsibillty/(?P<taskprofile_id>\w+)/priority/(?P<priority_int>\w+)/$', views.switch_assign_responsibillty, name='switch_assign_responsibillty'),
    url(r'^remove_assign_responsibillty/(?P<taskprofile_id>\w+)/$', views.remove_assign_responsibillty, name='remove_assign_responsibillty'),

    url(r'^add_domain/(?P<task_id>\w+)/$', views.add_domain, name='add_domain'),

    url(r'^task_link/(?P<tasklink_id>\w+)/unlink/$', views.task_unlink, name='task_unlink'),

    path( 'task_domain/<taskdomain_id>/unlink', views.project_task_domain_unlink, name='project_task_domain_unlink'),

    url(r'^task_comment/(?P<task_comment_id>\w+)/edit/$', views.edit_task_comment, name='edit_task_comment'),
    url(r'^task_comment/(?P<task_comment_id>\w+)/history/$', views.task_comment_history, name='task_comment_history'),

    url(r'^task_check/(?P<task_check_id>\w+)/switch/$', views.task_check_switch, name='task_check_switch'),

    url(r'^milestone_add/(?P<project_id>\w+)/$', views.MilestoneCreateView.as_view(), name='milestone_add'),
    url(r'^milestone/(?P<pk>\w+)/edit/$', views.MilestoneUpdateView.as_view(), name='milestone_edit'),
    url(r'^milestone/(?P<milestone_id>\w+)/$', views.milestone_view, name='milestone_view'),
    url(r'^milestone/(?P<milestone_id>\w+)/history/$', views.milestone_history, name='milestone_history'),

    url(r'^schedule/view_my_index/$', views.view_my_schedule, name='view_my_index_schedule'),
    url(r'^schedule/view_profile_index/(?P<profile_id>\w+)/$', views.view_profile_schedule, name='view_profile_schedule'),
    url(r'^schedule_add_current/$', views.create_schedule_current, name='create_schedule_current'),
    url(r'^schedule_add_current/(?P<profile_id>\w+)/$', views.create_schedule_current, name='create_schedule_current'),
    url(r'^schedule_add_next/$', views.create_schedule_next, name='create_schedule_next'),
    url(r'^schedule_add_next/(?P<profile_id>\w+)/$', views.create_schedule_next, name='create_schedule_next'),
    url(r'^schedule/(?P<schedule_item_id>\w+)/$', views.schedule_item_view, name='schedule_item_view'),

    url(r'^schedule/(?P<schedule_item_id>\w+)/schedule_one_task/(?P<task_id>\w+)$', views.schedule_one_task, name='schedule_one_task'),
    url(r'^schedule/(?P<schedule_item_id>\w+)/unschedule_one_task/(?P<task_id>\w+)$', views.unschedule_one_task, name='unschedule_one_task'),

    ]

project/forms.py
# project forms

from django import forms
from project.models import Project, PROJECT_VISIBLE_LIST_CHOICES, PROJECT_VISIBLE_PRIVATE, Task, TaskComment, Milestone, Member, TaskDomain, TaskLink, TaskProfile, TASK_PROFILE_PRIORITY_LIST, TASK_PROFILE_PRIORITY_INTERESTED, TASK_PROFILE_PRIORITY_LIST_CHOICES, TaskCheckList, Task2Domain, Get_Profiles_Available2Task, Sub_Project, Task_Property_Amount
from ich_bau.profiles.models import PROFILE_TYPE_USER

from django.forms.widgets import HiddenInput, CheckboxSelectMultiple
from mptt.forms import TreeNodeChoiceField

from commons.editors import DateTime_Field, TextEditor_Field

class ProjectForm(forms.ModelForm):
    description = TextEditor_Field(arg_required=False)
    # https://docs.djangoproject.com/en/2.2/ref/forms/api/#dynamic-initial-values
    # https://docs.djangoproject.com/en/2.2/ref/forms/widgets/#widgets-inheriting-from-the-select-widget
    private_type = forms.ChoiceField( label='Project visible level',
                                      widget=forms.RadioSelect,
                                      choices=PROJECT_VISIBLE_LIST_CHOICES,
                                      initial = PROJECT_VISIBLE_PRIVATE )

    class Meta:
        model = Project
        fields = ['fullname', 'private_type', 'active_flag', 'use_sub_projects', 'use_properties', 'description' ]

class MilestoneForm(forms.ModelForm):
    planned_at = DateTime_Field( False )
    finished_at = DateTime_Field( False )

    class Meta:
        model = Milestone
        fields = ['fullname', 'planned_at', 'finished_at' ]

from ich_bau.profiles.models import Profile, Get_Users_Profiles

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ['member_profile', 'admin_flag' ]

    def __init__(self, *args, **kwargs):
        super(MemberForm, self).__init__(*args, **kwargs)
        # форма работает в режиме создания (смотрим 'initial')
        p = kwargs.pop('initial', None)['project']

        # отображать только свободных людей
        if not ( p is None):
            self.fields['member_profile'].queryset = Get_Users_Profiles().exclude( member_profile__project_id = p.id )

class TaskForm(forms.ModelForm):
    description = TextEditor_Field(arg_required=False)

    class Meta:
        model = Task
        fields = ['fullname', 'description', 'milestone', 'holder', 'important', 'kind', 'sub_project' ]

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        # форма работает в 2х режимах - создания (смотрим 'initial') и редактирования (смотрим 'instance') свойства.
        instance = kwargs.pop('instance', None)
        if (instance is None):
            pop = kwargs.pop('initial', None)
            p = pop['project']
        else:
            p = instance.project

        # отображать вехи, подпроекты и пользователей только этого проекта
        if not ( p is None):
            self.fields['milestone'].queryset = Milestone.objects.filter( project = p, finished_at__isnull = True )
            if p.use_sub_projects:
                self.fields['sub_project'].queryset = Sub_Project.objects.filter( project = p )
            else:
                self.fields['sub_project'].widget = HiddenInput()

            list = p.GetFullMemberProfiles()
            self.fields['holder'].queryset = list

class TaskLinkedForm(forms.ModelForm):
    subtasks=forms.ModelMultipleChoiceField( Task.objects, help_text="subtask", required=True, widget=CheckboxSelectMultiple() )

    def __init__(self, *args, **kwargs):
        arg_qs = kwargs.pop('arg_qs', None)
        super(TaskLinkedForm, self).__init__(*args, **kwargs)

        if ( arg_qs != "" ):
            self.fields['subtasks'].queryset = arg_qs

    class Meta:
        model = TaskLink
        fields = ['subtasks']

class TaskProfileForm(forms.ModelForm):
    profile=forms.ModelChoiceField( Profile.objects,
                                    help_text="profile",
                                    widget=forms.RadioSelect,
                                    required=True )
    # forms.BooleanField( label = 'Responsible', help_text="Responsible or interested", required=False )
    priority=forms.ChoiceField( label='Priority',
                                      widget=forms.RadioSelect,
                                      choices=TASK_PROFILE_PRIORITY_LIST_CHOICES,
                                      initial = TASK_PROFILE_PRIORITY_INTERESTED )

    def __init__(self, *args, **kwargs):
        argmaintaskid = kwargs.pop('argmaintaskid', None)
        q = kwargs.pop('arg_query_for_combo', None)
        super(TaskProfileForm, self).__init__(*args, **kwargs)
        self.fields['profile'].queryset = q

    class Meta:
        model = TaskProfile
        fields = ['profile', 'priority' ]

class TaskDomainForm(forms.ModelForm):
    taskdomain = TreeNodeChoiceField(queryset=TaskDomain.objects.all())

    def __init__(self, *args, **kwargs):
        argmaintaskid = kwargs.pop('argmaintaskid', None)
        super(TaskDomainForm, self).__init__(*args, **kwargs)

        if (argmaintaskid != "" ):
            #main_task = Task.objects.get( id = argmaintaskid )
            self.fields['taskdomain'].queryset = TaskDomain.objects.all().exclude( domain2task__task = argmaintaskid )

    class Meta:
        model = Task2Domain
        fields = ['taskdomain']

class TaskCommentForm(forms.ModelForm):
    comment = TextEditor_Field()

    class Meta:
        model = TaskComment
        fields = ['comment' ]

class TaskCheckListForm(forms.ModelForm):
    class Meta:
        model = TaskCheckList
        fields = ['checkname', 'check_flag' ]


class Sub_ProjectForm(forms.ModelForm):
    class Meta:
        model = Sub_Project
        fields = ['fullname',  ]

class Task_Property_Amount_Form(forms.ModelForm):

    class Meta:
        model = Task_Property_Amount
        fields = [ 'property', 'amount' ]

    def __init__(self, *args, **kwargs):
        allowed_properties = kwargs.pop('arg_allowed_properties', None)
        super(Task_Property_Amount_Form, self).__init__(*args, **kwargs)

        if allowed_properties is None:
            self.fields['property'].widget = HiddenInput()
        else:
            self.fields['property'].queryset = allowed_properties

project/templates/project/milestone.html
{% extends 'site_base.html' %}

{% load i18n %}
{% load bootstrap %}

{% block head_title %}{{milestone}}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
        
<ol class="breadcrumb">
<li> <a href="{% url 'project:index' %}">Projects</a></li></li>
<li> <a href="{{ milestone.project.get_absolute_url }}">{{ milestone.project }}</a></li>
<li> <a href="{% url 'project:project_view_milestones' milestone.project.id %}">{{ milestone.project }} milestones</a> </li>
</ol>
        
<h1>{{milestone}}</h1>

<p>{% if milestone.planned_at %}Plan date: {{milestone.planned_at|date}} {% endif %}</p>
<p>{% if milestone.finished_at %}Fact finish date: {{milestone.finished_at|date}} {% endif %}</p>

{% if user_can_admin %}
<a class="btn btn-default" href="{{milestone.get_absolute_url}}edit"><i class="fa fa-pencil-square-o"></i> Edit milestone</a>

{% if milestone.created_at == milestone.modified_at %}
no history to view

{% else %}
<a href="{{milestone.get_absolute_url}}history">History</a>
{% endif %}

{% endif %}

<h2>Tasks {% if not milestone.finished_at %}{% if user_can_admin or user_can_work %}<a class="btn btn-default" href="/project/task_add_to_milestone/{{milestone.id}}/"><i class="fa fa-plus"></i> {% trans "Create task" %}</a>{% endif %}{% endif %}</h2>

{% include "project/task_list.html" with table_mode='milestone' %}

</div>
</div>

<small>This page was last modified on {{ milestone.modified_at }}</small>
    
{% endblock %}

project/templates/project/project.html
{% extends 'site_base.html' %}

{% load i18n %}
{% load bootstrap %}
{% load thumbnail %}
{% load template_arithmetic_tag %}

{% block head_title %}{{project}}{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
<h1>{{project}}
{% if not project.is_project_visible %}
<i class="fa fa-lock"></i>
{% endif %}

{% if not project.active_flag %}
   <span class="label label-primary">Closed</span>
{% endif %}

</h1>

<ul class="nav nav-tabs">
  <li role="presentation" {% if show_page == 'title' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}">{% trans "Project" %}</a></li>
  {% if project.use_sub_projects %}
  <li role="presentation" {% if show_page == 'sub_projects' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}sub_projects/">{% trans "Sub projects" %}</a></li>
  {% endif %}
  <li role="presentation" {% if show_page == 'members' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}members/">{% trans "Members" %}</a></li>
  <li role="presentation" {% if show_page == 'last_actions' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}last_actions/">{% trans "Last activities" %}</a></li>

  {% if show_file_page %}
    <li role="presentation" {% if show_page == 'files' %} class="active" {% endif %}><a href="{% url 'project:project_view_files' project_id=project.pk %}">{% trans "Files" %}</a></li>
  {% endif %}
  <li role="presentation" {% if show_page == 'milestones' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}milestones/">{% trans "Milestones" %}</a></li>
  <li role="presentation" {% if show_page == 'reports' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}reports/">{% trans "Reports" %}</a></li>
</ul>

{% if show_page == 'title' %}

<p>Project description</p>

{% if project.description %}
{{ project.description_html|safe }}
{% endif %}

{% if user_can_admin %}
<a class="btn btn-default" href="{{project.get_absolute_url}}project_edit"><i class="fa fa-pencil-square-o"></i> {% trans "Edit project" %}</a>
{% endif %}

{% if project.created_at == project.modified_at %}
no history to view

{% else %}
<a href="{{project.get_absolute_url}}history">History</a>
{% endif %}

<h2>{% trans "Tasks" %} {% if user_can_admin or user_can_work %}<a class="btn btn-default" href="/project/task_add/{{project.id}}/"><i class="fa fa-plus"></i> {% trans "Create task" %}</a>{% endif %}</h2>

<ul class="nav nav-tabs">
  <li role="presentation" {% if filter_type == '' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}">{% trans "Open" %}</a></li>
  <li role="presentation" {% if filter_type == 'filter_task_closed' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}closed_task/">{% trans "Closed" %}</a></li>
  <li role="presentation" {% if filter_type == 'filter_task_assigned' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}assigned_task/">{% trans "Assigned" %}</a></li>
  <li role="presentation" {% if filter_type == 'filter_task_unassigned' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}unassigned_task/">{% trans "Unassigned" %}</a></li>
  <li role="presentation" {% if filter_type == 'filter_task_by_domain' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}task_by_domain/">{% trans "Domain" %}</a></li>
  <li role="presentation" {% if filter_type == 'filter_task_search' %} class="active" {% endif %}><a href="{{project.get_absolute_url}}search_task/">{% trans "Search" %}</a></li>
</ul>

{% if filter_type == 'filter_task_search' %}
    <div class="row">
        <div class="col-md-5">

    <form action="" method="get">
        {{ filter.form|bootstrap }}
        <input type="submit" class="btn btn-info" />
    </form>
    </div>
    </div>
{% else %}
    {% if filter_type == 'filter_task_by_domain' %}
        {% load mptt_tags %}

        <div class="row">
          <div class="col-md-5">
            <br>
            <ul>
                {% if selected_domain == None %}
                <strong>
                {% endif %}
                <p><a href="{{project.get_absolute_url}}task_by_domain/">Tasks without domains</a></p>
                {% if selected_domain == None %}
                </strong>
                {% endif %}

                {% recursetree domains %}
                    <li>
                    {% if node.pk == selected_domain %}<strong>{% endif %}
                    <a href="{% url 'project:project_view_task_for_domain' project.pk node.pk %}">{{node.name}}</a>
                    {% if node.pk == selected_domain %}</strong>{% endif %}
                        {% if not node.is_leaf_node %}
                            <ul>
                            {{ children }}
                            </ul>
                        {% endif %}
                    </li>
                {% endrecursetree %}
            </ul>
          <p>
          {% if selected_domain == None %}
            <a href="{% url 'project:task_search_by_domain' %}" class="btn btn-default">Search for all tasks without domains</a>
          {% else %}
            <a href="{% url 'project:task_search_by_domain_selected' selected_domain %}" class="btn btn-default">Search for all tasks for this domain</a>
          {% endif %}
          </p>
          </div>
        </div>
    {% endif %}

{% endif %}

{% include "project/task_list.html" with table_mode='project' show_assignee_flag=show_assignee_flag %}

{% comment %} end if TITLE {% endcomment %}
{% endif %}

{% if show_page == 'members' %}

<h2>{% trans "Members" %} {% if user_can_admin %}<a class="btn btn-default" href="/project/member_add/{{project.id}}/"><i class="fa fa-plus"></i> {% trans "Add member" %}</a>{% endif %}</h2>

{% include "project/project_members_list.html" %}
{% endif %}

{% if show_page == 'sub_projects' %}

<h2>{% trans "Sub projects" %} {% if user_can_admin or user_can_work %}<a class="btn btn-default" href="{% url 'project:sub_project_add' project_id=project.id %}"><i class="fa fa-plus"></i> {% trans "Create sub project" %}</a>{% endif %}</h2>

<ul>
{% for sp in sub_projects %}
<li><a href="{{sp.get_absolute_url}}">{{sp}}</a></li>
{% endfor %}
</ul>

<h3>List of opened tasks without a sub-project</h3>
<ol>
{% for t in open_tasks_without_subproject %}
<li><a href="{{t.get_absolute_url}}">{{t}}</a></li>
{% endfor %}
</ol>
{% endif %}

{% if show_page == 'last_actions' %}

<h2>{% trans "Recent project activity" %}</h2>

<table class="table table-striped">
<thead>
<tr>
    <th>Type</th>
    <th>Date time</th>
    <th>Action</th>
    <th>User</th>
</tr>
</thead>

<tbody>
    {% for la in last_actions %}
        <tr>
            <td>{{la.type}}</td>
            <td>{{la.modified_at}}</td>
            <td>
                {{la.title|safe|truncatewords_html:12}}
                <a href="{{la.url}}">{{la.url_title}}</a>
            </td>
            <td>{{la.modified_user}}</td>
        </tr>
    {%endfor%}
</tbody>
</table>

{% endif %}


{% if show_page == 'files' %}
<h2>Files</h2>

{% include "project/project_repo.html" %}


{% comment %} end if FILES {% endcomment %}
{% endif %}

{% if show_page == 'milestones' %}
<h2>{% trans "Milestones" %}{% if user_can_admin %} <a class="btn btn-default" href="/project/milestone_add/{{project.id}}/"><i class="fa fa-plus"></i> {% trans "Create milestone" %}</a>{% endif %}</h2>

{% include "project/project_milestones.html" %}

{% comment %} end if MILESTONES {% endcomment %}
{% endif %}


{% if show_page == 'reports' %}
<h2>{% trans "Reports" %}</h2>

<p><a href="{% url 'project:project_view_report_all_tasks' project.id %}" target="_blank">Download all tasks report (new window)</a></p>


<h3>EXCEL</h3>

<p><a href="{% url 'project:project_view_report_all_tasks_xls' project.id %}" target="_blank">Download all tasks report (as Excel)</a></p>

{% endif %}


</div>
</div>

{% endblock %}