crm/urls.py
from django.conf.urls import url

from crm import views
app_name = 'crm'

urlpatterns = [
    url(r'^$', views.ContractListView.as_view(), name="contracts_list"),

    url(r'^contract_add/$', views.ContractCreateView.as_view(), name='contract_add'),
    url(r'^contract/(?P<contract_id>\w+)/$', views.contract_view, name='contract_view'),
    url(r'^contract/(?P<contract_id>\w+)/contract_edit/$', views.contract_edit, name='contract_edit'),
    url(r'^contract/(?P<contract_id>\w+)/history/$', views.contract_history, name='contract_history'),
    ]

ich_bau/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from django.contrib import admin

from .views import get_homepage

from .profiles.views import ProfileCreateView, ProfileCreateSubView, ProfileDetailView, ProfileUpdateView, my_profile_view, ProfileEditView, ProfileListView, notifications_view_unread, notifications_view_unread_by_type, notifications_view_read, notification_read

urlpatterns = [
    url(r"^$", get_homepage, name="home"),
    url(r"^admin/", admin.site.urls),
    url(r"^account/", include("account.urls")),
    url(r'^summernote/', include('django_summernote.urls')),

    url(r"^profile/view/", my_profile_view, name="my_profile_view"),
    url(r"^profile/edit/", ProfileEditView.as_view(), name="profiles_edit"),
    url(r"^p/$", ProfileListView.as_view(), name="profiles_list"),
    url(r"^p/(?P<pk>\w+)/$", ProfileDetailView.as_view(), name="profiles_detail"),
    url(r"^p/(?P<pk>\w+)/edit/$", ProfileUpdateView.as_view(), name="profile_update"),
    url(r"^p/create$", ProfileCreateView.as_view(), name="profile_create"),
    url(r"^p/(?P<pk>\w+)/add_sub/$", ProfileCreateSubView.as_view(), name="profile_add_sub"),
    url(r"^p/(?P<pk>\w+)/level/(?P<level_pk>\w+)/add_sub/$", ProfileCreateSubView.as_view(), name="profile_add_sub_tree_view"),

    url(r"^notifications/$", notifications_view_unread, name="unread_notifications_view"),
    url(r"^notifications_by_type/$", notifications_view_unread_by_type, name="unread_notifications_view_by_type"),
    url(r"^notifications/read/$", notifications_view_read, name="read_notifications_view"),
    url(r"^notification/(?P<notification_id>\w+)/$", notification_read, name="notification_read"),

    url(r"^support/", include('support.urls', namespace="support") ),
    url(r"^project/", include('project.urls', namespace="project") ),
    url(r"^crm/", include('crm.urls', namespace="crm") ),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/urls.py
from django.conf.urls import url
from django.urls import path

from project import views

app_name = 'project'

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^all_available/$', views.index_available, name='all_available'),
    url(r'^all_public/$', views.index_public, name='all_public'),
    url(r'^search_public/$', views.index_search_public, name='search_public'),
    url(r'^task_search/$', views.index_task_search, name='task_search'),
    url(r'^task_search_by_domain/$', views.index_task_search_by_domain, name='task_search_by_domain'),
    url(r'^task_search_by_domain/selected/(?P<domain_id>\w+)/$', views.index_task_search_by_domain, name='task_search_by_domain_selected'),

    url(r'^project_add/$', views.ProjectCreateView.as_view(), name='project_add'),
    url(r'^project/(?P<project_id>\w+)/project_edit/$', views.project_edit, name='project_edit'),

    url(r'^project/(?P<project_id>\w+)/$', views.project_view, name='project_view'),
    url(r'^project/(?P<project_id>\w+)/history/$', views.project_history, name='project_history'),
    url(r'^project/(?P<project_id>\w+)/closed_task/$', views.project_view_closed_tasks, name='project_view_closed_tasks'),
    url(r'^project/(?P<project_id>\w+)/assigned_task/$', views.project_view_assigned_tasks, name='project_view_assigned_tasks'),
    url(r'^project/(?P<project_id>\w+)/unassigned_task/$', views.project_view_unassigned_tasks, name='project_view_unassigned_tasks'),

    # django v.2 path
    path( 'project/<project_id>/task_by_domain/', views.project_view_task_by_domain, name='project_view_task_by_domain'),
    path( 'project/<project_id>/task_by_domain/<domain_id>/', views.project_view_task_by_domain, name='project_view_task_for_domain'),

    url(r'^project/(?P<project_id>\w+)/search_task/$', views.project_view_search_tasks, name='project_view_search_tasks'),

    url(r'^project/(?P<project_id>\w+)/last_actions/$', views.project_view_last_actions, name='project_view_last_actions'),
    url(r'^project/(?P<project_id>\w+)/sub_projects/$', views.project_view_sub_projects, name='project_view_sub_projects'),
    url(r'^project/(?P<project_id>\w+)/members/$', views.project_view_members, name='project_view_members'),
    url(r'^project/(?P<project_id>\w+)/milestones/$', views.project_view_milestones, name='project_view_milestones'),
    url(r'^project/(?P<project_id>\w+)/reports/$', views.project_view_reports, name='project_view_reports'),

    url(r'^project/(?P<project_id>\w+)/report_all_tasks/$', views.project_view_report_all_tasks, name='project_view_report_all_tasks'),
    url(r'^project/(?P<project_id>\w+)/report_all_tasks_xls/$', views.project_view_report_all_tasks_xls.as_view(), name='project_view_report_all_tasks_xls'),
    # repo urls
    url(r'^project/(?P<project_id>\w+)/files/$', views.project_view_files, name='project_view_files'),
    url(r'^project/(?P<project_id>\w+)/files/commit/(?P<rev_id>\w+)/$', views.project_view_file_commit_view, name='project_view_file_commit_view'),
    url(r'^project/(?P<project_id>\w+)/create_repo/$', views.project_create_repo, name='project_create_repo'),

    url(r'^member_add/(?P<project_id>\w+)/$', views.AddMemberCreateView.as_view(), name='member_add'),
    url(r'^member_want_join/(?P<project_id>\w+)/$', views.member_want_join, name='member_want_join'),
    url(r'^member/(?P<member_id>\w+)/member_accept/$', views.member_accept, name='member_accept'),
    url(r'^member/(?P<member_id>\w+)/team_accept/$', views.team_accept, name='team_accept'),
    url(r'^member/(?P<member_id>\w+)/remove_check/$', views.member_remove_check, name='member_remove_check'),
    url(r'^member/(?P<member_id>\w+)/remove_confirm/$', views.member_remove_confirm, name='member_remove_confirm'),

    url(r'^task_add/(?P<project_id>\w+)/$', views.TaskCreateView.as_view(), name='task_add'),
    url(r'^task_add_to_milestone/(?P<milestone_id>\w+)/$', views.TaskCreateView.as_view(), name='task_add_to_milestone'),
    url(r'^task/(?P<pk>\w+)/edit/$', views.TaskUpdateView.as_view(), name='task_edit'),
    url(r'^task/(?P<task_id>\w+)/checklist/$', views.task_checklist, name='task_checklist'),
    url(r'^task/(?P<task_id>\w+)/$', views.task_view, name='task_view'),
    url(r'^task/(?P<task_id>\w+)/history/$', views.task_history, name='task_history'),
    url(r'^add_linked/(?P<task_id>\w+)/$', views.add_linked, name='add_linked'),

    url(r'^task/(?P<task_id>\w+)/add_property/$', views.task_add_property, name='task_add_property'),
    url(r'^task/(?P<task_property_id>\w+)/edit_property/$', views.task_edit_property, name='task_edit_property'),

    url(r'^sub_project_add/(?P<project_id>\w+)/$', views.Sub_ProjectCreateView.as_view(), name='sub_project_add'),
    url(r'^sub_project/(?P<sub_project_id>\w+)/$', views.sub_project_view, name='sub_project_view'),
    url(r'^sub_project/(?P<pk>\w+)/edit/$', views.Sub_ProjectUpdateView.as_view(), name='sub_project_edit'),
    url(r'^sub_project/(?P<sub_project_id>\w+)/history/$', views.sub_project_history, name='sub_project_history'),

    url(r'^task_move2project_dialog/(?P<task_id>\w+)/$', views.task_move2project, name='task_move2project_dialog'),
    url(r'^task_move2project_check/(?P<task_id>\w+)/target_project/(?P<project_id>\w+)/$', views.task_move2project, name='task_move2project_check'),

    url(r'^add_profile/(?P<task_id>\w+)/$', views.add_profile, name='add_profile'),
    url(r'^add_profile/(?P<task_id>\w+)/level/(?P<level_pk>\w+)/$', views.add_profile, name='add_profile_sub_tree_view'),
    url(r'^add_user/(?P<task_id>\w+)/$', views.add_user, name='add_user'),
    url(r'^switch_assign_responsibillty/(?P<taskprofile_id>\w+)/priority/(?P<priority_int>\w+)/$', views.switch_assign_responsibillty, name='switch_assign_responsibillty'),
    url(r'^remove_assign_responsibillty/(?P<taskprofile_id>\w+)/$', views.remove_assign_responsibillty, name='remove_assign_responsibillty'),

    url(r'^add_domain/(?P<task_id>\w+)/$', views.add_domain, name='add_domain'),

    url(r'^task_link/(?P<tasklink_id>\w+)/unlink/$', views.task_unlink, name='task_unlink'),

    path( 'task_domain/<taskdomain_id>/unlink', views.project_task_domain_unlink, name='project_task_domain_unlink'),

    url(r'^task_comment/(?P<task_comment_id>\w+)/edit/$', views.edit_task_comment, name='edit_task_comment'),
    url(r'^task_comment/(?P<task_comment_id>\w+)/history/$', views.task_comment_history, name='task_comment_history'),

    url(r'^task_check/(?P<task_check_id>\w+)/switch/$', views.task_check_switch, name='task_check_switch'),

    url(r'^milestone_add/(?P<project_id>\w+)/$', views.MilestoneCreateView.as_view(), name='milestone_add'),
    url(r'^milestone/(?P<pk>\w+)/edit/$', views.MilestoneUpdateView.as_view(), name='milestone_edit'),
    url(r'^milestone/(?P<milestone_id>\w+)/$', views.milestone_view, name='milestone_view'),
    url(r'^milestone/(?P<milestone_id>\w+)/history/$', views.milestone_history, name='milestone_history'),

    url(r'^schedule/view_my_index/$', views.view_my_schedule, name='view_my_index_schedule'),
    url(r'^schedule/view_profile_index/(?P<profile_id>\w+)/$', views.view_profile_schedule, name='view_profile_schedule'),
    url(r'^schedule_add_current/$', views.create_schedule_current, name='create_schedule_current'),
    url(r'^schedule_add_current/(?P<profile_id>\w+)/$', views.create_schedule_current, name='create_schedule_current'),
    url(r'^schedule_add_next/$', views.create_schedule_next, name='create_schedule_next'),
    url(r'^schedule_add_next/(?P<profile_id>\w+)/$', views.create_schedule_next, name='create_schedule_next'),
    url(r'^schedule/(?P<schedule_item_id>\w+)/$', views.schedule_item_view, name='schedule_item_view'),

    url(r'^schedule/(?P<schedule_item_id>\w+)/schedule_one_task/(?P<task_id>\w+)$', views.schedule_one_task, name='schedule_one_task'),
    url(r'^schedule/(?P<schedule_item_id>\w+)/unschedule_one_task/(?P<task_id>\w+)$', views.unschedule_one_task, name='unschedule_one_task'),

    ]

ich_bau/templates/_account_bar.html
{% load i18n %}
{% load account_tags %}
{% load ynotification %}

<ul class="nav navbar-nav pull-right">
    {% if request.user.is_authenticated %}
        <li>
            <a href="{% url 'unread_notifications_view' %}"> {% unread_notification_count %} </a>
        </li>
        <li>
            <a href="{% url 'my_profile_view' %}"><i class="fa fa-user"></i> {% user_display request.user %}</a>
        </li>
        <li>
            <a href="{% url 'account_settings' %}"><i class="fa fa-cog"></i> {% trans "Settings" %}</a>
        </li>
        <li>
            <a id="account_logout" href="{% url 'account_logout' %}"><i class="fa fa-power-off"></i> {% trans "Log out" %}</a>
        </li>
    {% else %}
        <li><a href="{% url 'account_login' %}">{% trans "Log in" %}</a></li>
        {% if ACCOUNT_OPEN_SIGNUP %}
            <li><a href="{% url 'account_signup' %}">{% trans "Sign up" %}</a></li>
        {% endif %}
    {% endif %}
</ul>

<form id="accountLogOutForm" style="display: none;" action="{% url 'account_logout' %}" method="POST">
    {% csrf_token %}
</form>

ich_bau/templates/_footer.html
{% load i18n %}
{% load version_info %}

{% site_version_info %}

{% trans "&copy; PostPDM" %}

ich_bau/templates/_scripts.html
<script src='/site_media/static/js/site-5e73bbeeb0.js'></script>

ich_bau/templates/_styles.html
<link href='/site_media/static/css/site-e7b87bbea0.css' rel='stylesheet' />

ich_bau/templates/homepage.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}Ich bau{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
    <section class="jumbotron">
        <div class="container">
            {% include "_messages.html" %}
            <h1>{% blocktrans %}Welcome to 'Ich bau' project{% endblocktrans %}</h1>
            <p>
                {% blocktrans %}
                "Zero" project.
                {% endblocktrans %}
            </p>
            {% if not user.is_authenticated %}
            {% url "account_login" as login_url %}
            {% url "account_signup" as signup_url %}
            <p>{% blocktrans %}You can <a href="{{ login_url }}" class="btn btn-default">Log In</a> or <a href="{{ signup_url }}" class="btn btn-primary">Sign Up</a> to try out the site.{% endblocktrans %}</p>
            {% endif %}
        </div>
    </section>
    <section>
        <div class="container">
            <h2 class="text-center">{% blocktrans %}What is Ich bau?{% endblocktrans %}</h2>
            <p class="lead">
                {% blocktrans %}
                <b>Ich bau</b> is an open-source project based on Django.
                {% endblocktrans %}
            </p>
            <div class="feature-columns">
                <div>
                    <i class="fa fa-cubes fa-3x"></i><br>
                    {% blocktrans %}
                    Plan.
                    {% endblocktrans %}
                </div>
                <div>
                    <i class="fa fa-puzzle-piece fa-3x"></i><br>
                    {% blocktrans %}
                    Collaborate.
                    {% endblocktrans %}
                </div>
                <div>
                    <i class="fa fa-tint fa-3x"></i><br>
                    {% blocktrans %}
                    Create!
                    {% endblocktrans %}
                </div>
            </div>
        </div>
    </section>

    {% if apps_html_blocks %}
        <section>
            <div class="container">
                <p class="lead text-center">
                    {{apps_html_blocks|safe}}
                </p>
            </div>
        </section>
    {% endif %}

    <section>
        <div class="container">
            <p class="lead text-center">
                {% blocktrans %}
                See <a href="https://github.com/postpdm/ich_bau">github.com/postpdm/ich_bau</a>
                for more information.
                {% endblocktrans %}
            </p>
        </div>
    </section>
{% endblock %}

ich_bau/templates/site_base.html
{% extends "theme_bootstrap/base.html" %}

{% load staticfiles %}
{% load i18n %}


{% block styles %}
    {% include "_styles.html" %}
{% endblock %}


{% block extra_head_base %}

{% load ynotification %}
{% main_message %}

    {% block extra_head %}{% endblock %}
{% endblock %}

{% block nav %}
    <ul class="nav navbar-nav pull-left">
      <li><a href="{% url 'support:index' %}">Support</a></li>
      <li><a href="{% url 'profiles_list' %}">Profiles</a></li>
      <li><a href="{% url 'project:index' %}">Projects</a></li>
      <li><a href="{% url 'project:view_my_index_schedule' %}">Schedule</a></li>
    </ul>
{% endblock %}


{% block footer %}
    {% include "_footer.html" %}
{% endblock %}


{% block scripts %}
    {% include "_scripts.html" %}
{% endblock %}

{% block extra_body_base %}

    {% block extra_body %}{% endblock %}
{% endblock %}